
GRPC_ADDRESS: ":3007"
GRPC_GATEWAY_ADDRESS: ":8082"

DATABASE_DSN: "postgres://gophkeeper_user:gophkeeper_pass@localhost:25432/gophkeeper_db?sslmode=disable"

MINIO:
  MINIO_ID: "minioadmin"
  MINIO_SECRET: "minioadmin"
  MINIO_BUCKET: "gophkeeper"
  MINIO_ADDRESS: "localhost:9000"