FROM node:22 AS builder

WORKDIR /app

RUN git clone https://github.com/apetsko/gophkeeper-frontend.git . \
    && npm install \
    && npm run dev:docker

FROM nginx:alpine

# Создаём директорию для SSL
RUN mkdir -p /etc/nginx/ssl

# Копируем билды
COPY --from=builder /app/dist /usr/share/nginx/html

# Копируем сертификаты
COPY --from=builder /app/deployment/certs ./certs

# Копируем кастомный конфиг nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf