// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/proto/v1/models/meta.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Meta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Meta) Reset() {
	*x = Meta{}
	mi := &file_api_proto_v1_models_meta_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Meta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Meta) ProtoMessage() {}

func (x *Meta) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_models_meta_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Meta.ProtoReflect.Descriptor instead.
func (*Meta) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_models_meta_proto_rawDescGZIP(), []int{0}
}

func (x *Meta) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

var File_api_proto_v1_models_meta_proto protoreflect.FileDescriptor

const file_api_proto_v1_models_meta_proto_rawDesc = "" +
	"\n" +
	"\x1eapi/proto/v1/models/meta.proto\x12\x13api.proto.v1.models\" \n" +
	"\x04Meta\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontentB)Z'gophkeeper/protogen/api/proto/v1/modelsb\x06proto3"

var (
	file_api_proto_v1_models_meta_proto_rawDescOnce sync.Once
	file_api_proto_v1_models_meta_proto_rawDescData []byte
)

func file_api_proto_v1_models_meta_proto_rawDescGZIP() []byte {
	file_api_proto_v1_models_meta_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_models_meta_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_models_meta_proto_rawDesc), len(file_api_proto_v1_models_meta_proto_rawDesc)))
	})
	return file_api_proto_v1_models_meta_proto_rawDescData
}

var file_api_proto_v1_models_meta_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_proto_v1_models_meta_proto_goTypes = []any{
	(*Meta)(nil), // 0: api.proto.v1.models.Meta
}
var file_api_proto_v1_models_meta_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_v1_models_meta_proto_init() }
func file_api_proto_v1_models_meta_proto_init() {
	if File_api_proto_v1_models_meta_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_models_meta_proto_rawDesc), len(file_api_proto_v1_models_meta_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_v1_models_meta_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_models_meta_proto_depIdxs,
		MessageInfos:      file_api_proto_v1_models_meta_proto_msgTypes,
	}.Build()
	File_api_proto_v1_models_meta_proto = out.File
	file_api_proto_v1_models_meta_proto_goTypes = nil
	file_api_proto_v1_models_meta_proto_depIdxs = nil
}
