// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: api/proto/v1/models/record.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Record struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Meta          *Meta                  `protobuf:"bytes,3,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_api_proto_v1_models_record_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_models_record_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_models_record_proto_rawDescGZIP(), []int{0}
}

func (x *Record) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Record) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Record) GetMeta() *Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

var File_api_proto_v1_models_record_proto protoreflect.FileDescriptor

const file_api_proto_v1_models_record_proto_rawDesc = "" +
	"\n" +
	" api/proto/v1/models/record.proto\x12\x13api.proto.v1.models\x1a\x1eapi/proto/v1/models/meta.proto\"[\n" +
	"\x06Record\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12-\n" +
	"\x04meta\x18\x03 \x01(\v2\x19.api.proto.v1.models.MetaR\x04metaB<Z:github.com/apetsko/gophkeeper/protogen/api/proto/v1/modelsb\x06proto3"

var (
	file_api_proto_v1_models_record_proto_rawDescOnce sync.Once
	file_api_proto_v1_models_record_proto_rawDescData []byte
)

func file_api_proto_v1_models_record_proto_rawDescGZIP() []byte {
	file_api_proto_v1_models_record_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_models_record_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_models_record_proto_rawDesc), len(file_api_proto_v1_models_record_proto_rawDesc)))
	})
	return file_api_proto_v1_models_record_proto_rawDescData
}

var file_api_proto_v1_models_record_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_proto_v1_models_record_proto_goTypes = []any{
	(*Record)(nil), // 0: api.proto.v1.models.Record
	(*Meta)(nil),   // 1: api.proto.v1.models.Meta
}
var file_api_proto_v1_models_record_proto_depIdxs = []int32{
	1, // 0: api.proto.v1.models.Record.meta:type_name -> api.proto.v1.models.Meta
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_v1_models_record_proto_init() }
func file_api_proto_v1_models_record_proto_init() {
	if File_api_proto_v1_models_record_proto != nil {
		return
	}
	file_api_proto_v1_models_meta_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_models_record_proto_rawDesc), len(file_api_proto_v1_models_record_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_v1_models_record_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_models_record_proto_depIdxs,
		MessageInfos:      file_api_proto_v1_models_record_proto_msgTypes,
	}.Build()
	File_api_proto_v1_models_record_proto = out.File
	file_api_proto_v1_models_record_proto_goTypes = nil
	file_api_proto_v1_models_record_proto_depIdxs = nil
}
