// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: api/proto/v1/rpc/bank_card.proto

package rpc

import (
	models "github.com/apetsko/gophkeeper/protogen/api/proto/v1/models"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BankCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardNumber    string                 `protobuf:"bytes,1,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`
	ExpiryDate    string                 `protobuf:"bytes,2,opt,name=expiry_date,json=expiryDate,proto3" json:"expiry_date,omitempty"`
	Cvv           string                 `protobuf:"bytes,3,opt,name=cvv,proto3" json:"cvv,omitempty"`
	Cardholder    string                 `protobuf:"bytes,4,opt,name=cardholder,proto3" json:"cardholder,omitempty"`
	Meta          *models.Meta           `protobuf:"bytes,5,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BankCardRequest) Reset() {
	*x = BankCardRequest{}
	mi := &file_api_proto_v1_rpc_bank_card_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BankCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BankCardRequest) ProtoMessage() {}

func (x *BankCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_rpc_bank_card_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BankCardRequest.ProtoReflect.Descriptor instead.
func (*BankCardRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_rpc_bank_card_proto_rawDescGZIP(), []int{0}
}

func (x *BankCardRequest) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

func (x *BankCardRequest) GetExpiryDate() string {
	if x != nil {
		return x.ExpiryDate
	}
	return ""
}

func (x *BankCardRequest) GetCvv() string {
	if x != nil {
		return x.Cvv
	}
	return ""
}

func (x *BankCardRequest) GetCardholder() string {
	if x != nil {
		return x.Cardholder
	}
	return ""
}

func (x *BankCardRequest) GetMeta() *models.Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type BankCardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BankCardResponse) Reset() {
	*x = BankCardResponse{}
	mi := &file_api_proto_v1_rpc_bank_card_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BankCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BankCardResponse) ProtoMessage() {}

func (x *BankCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_rpc_bank_card_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BankCardResponse.ProtoReflect.Descriptor instead.
func (*BankCardResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_rpc_bank_card_proto_rawDescGZIP(), []int{1}
}

func (x *BankCardResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_proto_v1_rpc_bank_card_proto protoreflect.FileDescriptor

const file_api_proto_v1_rpc_bank_card_proto_rawDesc = "" +
	"\n" +
	" api/proto/v1/rpc/bank_card.proto\x12\x10api.proto.v1.rpc\x1a\x1eapi/proto/v1/models/meta.proto\"\xb4\x01\n" +
	"\x0fBankCardRequest\x12\x1f\n" +
	"\vcard_number\x18\x01 \x01(\tR\n" +
	"cardNumber\x12\x1f\n" +
	"\vexpiry_date\x18\x02 \x01(\tR\n" +
	"expiryDate\x12\x10\n" +
	"\x03cvv\x18\x03 \x01(\tR\x03cvv\x12\x1e\n" +
	"\n" +
	"cardholder\x18\x04 \x01(\tR\n" +
	"cardholder\x12-\n" +
	"\x04meta\x18\x05 \x01(\v2\x19.api.proto.v1.models.MetaR\x04meta\",\n" +
	"\x10BankCardResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessageB9Z7github.com/apetsko/gophkeeper/protogen/api/proto/v1/rpcb\x06proto3"

var (
	file_api_proto_v1_rpc_bank_card_proto_rawDescOnce sync.Once
	file_api_proto_v1_rpc_bank_card_proto_rawDescData []byte
)

func file_api_proto_v1_rpc_bank_card_proto_rawDescGZIP() []byte {
	file_api_proto_v1_rpc_bank_card_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_rpc_bank_card_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_rpc_bank_card_proto_rawDesc), len(file_api_proto_v1_rpc_bank_card_proto_rawDesc)))
	})
	return file_api_proto_v1_rpc_bank_card_proto_rawDescData
}

var file_api_proto_v1_rpc_bank_card_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_v1_rpc_bank_card_proto_goTypes = []any{
	(*BankCardRequest)(nil),  // 0: api.proto.v1.rpc.BankCardRequest
	(*BankCardResponse)(nil), // 1: api.proto.v1.rpc.BankCardResponse
	(*models.Meta)(nil),      // 2: api.proto.v1.models.Meta
}
var file_api_proto_v1_rpc_bank_card_proto_depIdxs = []int32{
	2, // 0: api.proto.v1.rpc.BankCardRequest.meta:type_name -> api.proto.v1.models.Meta
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_v1_rpc_bank_card_proto_init() }
func file_api_proto_v1_rpc_bank_card_proto_init() {
	if File_api_proto_v1_rpc_bank_card_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_rpc_bank_card_proto_rawDesc), len(file_api_proto_v1_rpc_bank_card_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_v1_rpc_bank_card_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_rpc_bank_card_proto_depIdxs,
		MessageInfos:      file_api_proto_v1_rpc_bank_card_proto_msgTypes,
	}.Build()
	File_api_proto_v1_rpc_bank_card_proto = out.File
	file_api_proto_v1_rpc_bank_card_proto_goTypes = nil
	file_api_proto_v1_rpc_bank_card_proto_depIdxs = nil
}
