// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: api/proto/v1/rpc/binary_data.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	models "gophkeeper/protogen/api/proto/v1/models"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BinaryDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
	Meta          *models.Meta           `protobuf:"bytes,2,opt,name=meta" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BinaryDataRequest) Reset() {
	*x = BinaryDataRequest{}
	mi := &file_api_proto_v1_rpc_binary_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BinaryDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BinaryDataRequest) ProtoMessage() {}

func (x *BinaryDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_rpc_binary_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BinaryDataRequest.ProtoReflect.Descriptor instead.
func (*BinaryDataRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_rpc_binary_data_proto_rawDescGZIP(), []int{0}
}

func (x *BinaryDataRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *BinaryDataRequest) GetMeta() *models.Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type BinaryDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *string                `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BinaryDataResponse) Reset() {
	*x = BinaryDataResponse{}
	mi := &file_api_proto_v1_rpc_binary_data_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BinaryDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BinaryDataResponse) ProtoMessage() {}

func (x *BinaryDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_rpc_binary_data_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BinaryDataResponse.ProtoReflect.Descriptor instead.
func (*BinaryDataResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_rpc_binary_data_proto_rawDescGZIP(), []int{1}
}

func (x *BinaryDataResponse) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

var File_api_proto_v1_rpc_binary_data_proto protoreflect.FileDescriptor

const file_api_proto_v1_rpc_binary_data_proto_rawDesc = "" +
	"\n" +
	"\"api/proto/v1/rpc/binary_data.proto\x12\x10api.proto.v1.rpc\x1a\x1eapi/proto/v1/models/meta.proto\"V\n" +
	"\x11BinaryDataRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12-\n" +
	"\x04meta\x18\x02 \x01(\v2\x19.api.proto.v1.models.MetaR\x04meta\".\n" +
	"\x12BinaryDataResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessageB&Z$gophkeeper/protogen/api/proto/v1/rpcb\beditionsp\xe8\a"

var (
	file_api_proto_v1_rpc_binary_data_proto_rawDescOnce sync.Once
	file_api_proto_v1_rpc_binary_data_proto_rawDescData []byte
)

func file_api_proto_v1_rpc_binary_data_proto_rawDescGZIP() []byte {
	file_api_proto_v1_rpc_binary_data_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_rpc_binary_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_rpc_binary_data_proto_rawDesc), len(file_api_proto_v1_rpc_binary_data_proto_rawDesc)))
	})
	return file_api_proto_v1_rpc_binary_data_proto_rawDescData
}

var file_api_proto_v1_rpc_binary_data_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_v1_rpc_binary_data_proto_goTypes = []any{
	(*BinaryDataRequest)(nil),  // 0: api.proto.v1.rpc.BinaryDataRequest
	(*BinaryDataResponse)(nil), // 1: api.proto.v1.rpc.BinaryDataResponse
	(*models.Meta)(nil),        // 2: api.proto.v1.models.Meta
}
var file_api_proto_v1_rpc_binary_data_proto_depIdxs = []int32{
	2, // 0: api.proto.v1.rpc.BinaryDataRequest.meta:type_name -> api.proto.v1.models.Meta
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_v1_rpc_binary_data_proto_init() }
func file_api_proto_v1_rpc_binary_data_proto_init() {
	if File_api_proto_v1_rpc_binary_data_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_rpc_binary_data_proto_rawDesc), len(file_api_proto_v1_rpc_binary_data_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_v1_rpc_binary_data_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_rpc_binary_data_proto_depIdxs,
		MessageInfos:      file_api_proto_v1_rpc_binary_data_proto_msgTypes,
	}.Build()
	File_api_proto_v1_rpc_binary_data_proto = out.File
	file_api_proto_v1_rpc_binary_data_proto_goTypes = nil
	file_api_proto_v1_rpc_binary_data_proto_depIdxs = nil
}
