// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/proto/v1/rpc/binary_data.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Метаданные файла (отправляются один раз)
type FileMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	MimeType      string                 `protobuf:"bytes,2,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	MetaJson      string                 `protobuf:"bytes,3,opt,name=meta_json,json=metaJson,proto3" json:"meta_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileMetadata) Reset() {
	*x = FileMetadata{}
	mi := &file_api_proto_v1_rpc_binary_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileMetadata) ProtoMessage() {}

func (x *FileMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_rpc_binary_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileMetadata.ProtoReflect.Descriptor instead.
func (*FileMetadata) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_rpc_binary_data_proto_rawDescGZIP(), []int{0}
}

func (x *FileMetadata) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *FileMetadata) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *FileMetadata) GetMetaJson() string {
	if x != nil {
		return x.MetaJson
	}
	return ""
}

type BinaryDataRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*BinaryDataRequest_Metadata
	//	*BinaryDataRequest_Chunk
	Data          isBinaryDataRequest_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BinaryDataRequest) Reset() {
	*x = BinaryDataRequest{}
	mi := &file_api_proto_v1_rpc_binary_data_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BinaryDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BinaryDataRequest) ProtoMessage() {}

func (x *BinaryDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_rpc_binary_data_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BinaryDataRequest.ProtoReflect.Descriptor instead.
func (*BinaryDataRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_rpc_binary_data_proto_rawDescGZIP(), []int{1}
}

func (x *BinaryDataRequest) GetData() isBinaryDataRequest_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *BinaryDataRequest) GetMetadata() *FileMetadata {
	if x != nil {
		if x, ok := x.Data.(*BinaryDataRequest_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *BinaryDataRequest) GetChunk() []byte {
	if x != nil {
		if x, ok := x.Data.(*BinaryDataRequest_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

type isBinaryDataRequest_Data interface {
	isBinaryDataRequest_Data()
}

type BinaryDataRequest_Metadata struct {
	Metadata *FileMetadata `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"`
}

type BinaryDataRequest_Chunk struct {
	Chunk []byte `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

func (*BinaryDataRequest_Metadata) isBinaryDataRequest_Data() {}

func (*BinaryDataRequest_Chunk) isBinaryDataRequest_Data() {}

type BinaryDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,2,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BinaryDataResponse) Reset() {
	*x = BinaryDataResponse{}
	mi := &file_api_proto_v1_rpc_binary_data_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BinaryDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BinaryDataResponse) ProtoMessage() {}

func (x *BinaryDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_rpc_binary_data_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BinaryDataResponse.ProtoReflect.Descriptor instead.
func (*BinaryDataResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_rpc_binary_data_proto_rawDescGZIP(), []int{2}
}

func (x *BinaryDataResponse) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *BinaryDataResponse) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

var File_api_proto_v1_rpc_binary_data_proto protoreflect.FileDescriptor

const file_api_proto_v1_rpc_binary_data_proto_rawDesc = "" +
	"\n" +
	"\"api/proto/v1/rpc/binary_data.proto\x12\x10api.proto.v1.rpc\"e\n" +
	"\fFileMetadata\x12\x1b\n" +
	"\tfile_name\x18\x01 \x01(\tR\bfileName\x12\x1b\n" +
	"\tmime_type\x18\x02 \x01(\tR\bmimeType\x12\x1b\n" +
	"\tmeta_json\x18\x03 \x01(\tR\bmetaJson\"q\n" +
	"\x11BinaryDataRequest\x12<\n" +
	"\bmetadata\x18\x01 \x01(\v2\x1e.api.proto.v1.rpc.FileMetadataH\x00R\bmetadata\x12\x16\n" +
	"\x05chunk\x18\x02 \x01(\fH\x00R\x05chunkB\x06\n" +
	"\x04data\"L\n" +
	"\x12BinaryDataResponse\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x02 \x01(\x03R\tsizeBytesB&Z$gophkeeper/protogen/api/proto/v1/rpcb\x06proto3"

var (
	file_api_proto_v1_rpc_binary_data_proto_rawDescOnce sync.Once
	file_api_proto_v1_rpc_binary_data_proto_rawDescData []byte
)

func file_api_proto_v1_rpc_binary_data_proto_rawDescGZIP() []byte {
	file_api_proto_v1_rpc_binary_data_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_rpc_binary_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_rpc_binary_data_proto_rawDesc), len(file_api_proto_v1_rpc_binary_data_proto_rawDesc)))
	})
	return file_api_proto_v1_rpc_binary_data_proto_rawDescData
}

var file_api_proto_v1_rpc_binary_data_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_proto_v1_rpc_binary_data_proto_goTypes = []any{
	(*FileMetadata)(nil),       // 0: api.proto.v1.rpc.FileMetadata
	(*BinaryDataRequest)(nil),  // 1: api.proto.v1.rpc.BinaryDataRequest
	(*BinaryDataResponse)(nil), // 2: api.proto.v1.rpc.BinaryDataResponse
}
var file_api_proto_v1_rpc_binary_data_proto_depIdxs = []int32{
	0, // 0: api.proto.v1.rpc.BinaryDataRequest.metadata:type_name -> api.proto.v1.rpc.FileMetadata
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_v1_rpc_binary_data_proto_init() }
func file_api_proto_v1_rpc_binary_data_proto_init() {
	if File_api_proto_v1_rpc_binary_data_proto != nil {
		return
	}
	file_api_proto_v1_rpc_binary_data_proto_msgTypes[1].OneofWrappers = []any{
		(*BinaryDataRequest_Metadata)(nil),
		(*BinaryDataRequest_Chunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_rpc_binary_data_proto_rawDesc), len(file_api_proto_v1_rpc_binary_data_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_v1_rpc_binary_data_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_rpc_binary_data_proto_depIdxs,
		MessageInfos:      file_api_proto_v1_rpc_binary_data_proto_msgTypes,
	}.Build()
	File_api_proto_v1_rpc_binary_data_proto = out.File
	file_api_proto_v1_rpc_binary_data_proto_goTypes = nil
	file_api_proto_v1_rpc_binary_data_proto_depIdxs = nil
}
