// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: api/proto/v1/rpc/credentials.proto

package rpc

import (
	models "github.com/apetsko/gophkeeper/protogen/api/proto/v1/models"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CredentialsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Meta          *models.Meta           `protobuf:"bytes,3,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CredentialsRequest) Reset() {
	*x = CredentialsRequest{}
	mi := &file_api_proto_v1_rpc_credentials_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CredentialsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialsRequest) ProtoMessage() {}

func (x *CredentialsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_rpc_credentials_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialsRequest.ProtoReflect.Descriptor instead.
func (*CredentialsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_rpc_credentials_proto_rawDescGZIP(), []int{0}
}

func (x *CredentialsRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *CredentialsRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CredentialsRequest) GetMeta() *models.Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type CredentialsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CredentialsResponse) Reset() {
	*x = CredentialsResponse{}
	mi := &file_api_proto_v1_rpc_credentials_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CredentialsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialsResponse) ProtoMessage() {}

func (x *CredentialsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_rpc_credentials_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialsResponse.ProtoReflect.Descriptor instead.
func (*CredentialsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_rpc_credentials_proto_rawDescGZIP(), []int{1}
}

func (x *CredentialsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_proto_v1_rpc_credentials_proto protoreflect.FileDescriptor

const file_api_proto_v1_rpc_credentials_proto_rawDesc = "" +
	"\n" +
	"\"api/proto/v1/rpc/credentials.proto\x12\x10api.proto.v1.rpc\x1a\x1eapi/proto/v1/models/meta.proto\"u\n" +
	"\x12CredentialsRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12-\n" +
	"\x04meta\x18\x03 \x01(\v2\x19.api.proto.v1.models.MetaR\x04meta\"/\n" +
	"\x13CredentialsResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessageB9Z7github.com/apetsko/gophkeeper/protogen/api/proto/v1/rpcb\x06proto3"

var (
	file_api_proto_v1_rpc_credentials_proto_rawDescOnce sync.Once
	file_api_proto_v1_rpc_credentials_proto_rawDescData []byte
)

func file_api_proto_v1_rpc_credentials_proto_rawDescGZIP() []byte {
	file_api_proto_v1_rpc_credentials_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_rpc_credentials_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_rpc_credentials_proto_rawDesc), len(file_api_proto_v1_rpc_credentials_proto_rawDesc)))
	})
	return file_api_proto_v1_rpc_credentials_proto_rawDescData
}

var file_api_proto_v1_rpc_credentials_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_v1_rpc_credentials_proto_goTypes = []any{
	(*CredentialsRequest)(nil),  // 0: api.proto.v1.rpc.CredentialsRequest
	(*CredentialsResponse)(nil), // 1: api.proto.v1.rpc.CredentialsResponse
	(*models.Meta)(nil),         // 2: api.proto.v1.models.Meta
}
var file_api_proto_v1_rpc_credentials_proto_depIdxs = []int32{
	2, // 0: api.proto.v1.rpc.CredentialsRequest.meta:type_name -> api.proto.v1.models.Meta
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_v1_rpc_credentials_proto_init() }
func file_api_proto_v1_rpc_credentials_proto_init() {
	if File_api_proto_v1_rpc_credentials_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_rpc_credentials_proto_rawDesc), len(file_api_proto_v1_rpc_credentials_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_v1_rpc_credentials_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_rpc_credentials_proto_depIdxs,
		MessageInfos:      file_api_proto_v1_rpc_credentials_proto_msgTypes,
	}.Build()
	File_api_proto_v1_rpc_credentials_proto = out.File
	file_api_proto_v1_rpc_credentials_proto_goTypes = nil
	file_api_proto_v1_rpc_credentials_proto_depIdxs = nil
}
