// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/proto/v1/rpc/data_save.proto

package rpc

import (
	common "github.com/apetsko/gophkeeper/protogen/api/proto/v1/common"
	models "github.com/apetsko/gophkeeper/protogen/api/proto/v1/models"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DataSaveRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  common.DataType        `protobuf:"varint,1,opt,name=type,proto3,enum=api.proto.v1.common.DataType" json:"type,omitempty"`
	Meta  *models.Meta           `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	// Types that are valid to be assigned to Data:
	//
	//	*DataSaveRequest_BankCard
	//	*DataSaveRequest_Credentials
	//	*DataSaveRequest_BinaryData
	Data          isDataSaveRequest_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataSaveRequest) Reset() {
	*x = DataSaveRequest{}
	mi := &file_api_proto_v1_rpc_data_save_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataSaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataSaveRequest) ProtoMessage() {}

func (x *DataSaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_rpc_data_save_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataSaveRequest.ProtoReflect.Descriptor instead.
func (*DataSaveRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_rpc_data_save_proto_rawDescGZIP(), []int{0}
}

func (x *DataSaveRequest) GetType() common.DataType {
	if x != nil {
		return x.Type
	}
	return common.DataType(0)
}

func (x *DataSaveRequest) GetMeta() *models.Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *DataSaveRequest) GetData() isDataSaveRequest_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *DataSaveRequest) GetBankCard() *models.BankCard {
	if x != nil {
		if x, ok := x.Data.(*DataSaveRequest_BankCard); ok {
			return x.BankCard
		}
	}
	return nil
}

func (x *DataSaveRequest) GetCredentials() *models.Credentials {
	if x != nil {
		if x, ok := x.Data.(*DataSaveRequest_Credentials); ok {
			return x.Credentials
		}
	}
	return nil
}

func (x *DataSaveRequest) GetBinaryData() *models.File {
	if x != nil {
		if x, ok := x.Data.(*DataSaveRequest_BinaryData); ok {
			return x.BinaryData
		}
	}
	return nil
}

type isDataSaveRequest_Data interface {
	isDataSaveRequest_Data()
}

type DataSaveRequest_BankCard struct {
	BankCard *models.BankCard `protobuf:"bytes,3,opt,name=bank_card,json=bankCard,proto3,oneof"`
}

type DataSaveRequest_Credentials struct {
	Credentials *models.Credentials `protobuf:"bytes,4,opt,name=credentials,proto3,oneof"`
}

type DataSaveRequest_BinaryData struct {
	BinaryData *models.File `protobuf:"bytes,5,opt,name=binary_data,json=binaryData,proto3,oneof"`
}

func (*DataSaveRequest_BankCard) isDataSaveRequest_Data() {}

func (*DataSaveRequest_Credentials) isDataSaveRequest_Data() {}

func (*DataSaveRequest_BinaryData) isDataSaveRequest_Data() {}

type DataSaveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataSaveResponse) Reset() {
	*x = DataSaveResponse{}
	mi := &file_api_proto_v1_rpc_data_save_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataSaveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataSaveResponse) ProtoMessage() {}

func (x *DataSaveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_rpc_data_save_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataSaveResponse.ProtoReflect.Descriptor instead.
func (*DataSaveResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_rpc_data_save_proto_rawDescGZIP(), []int{1}
}

func (x *DataSaveResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_proto_v1_rpc_data_save_proto protoreflect.FileDescriptor

const file_api_proto_v1_rpc_data_save_proto_rawDesc = "" +
	"\n" +
	" api/proto/v1/rpc/data_save.proto\x12\x10api.proto.v1.rpc\x1a\x1eapi/proto/v1/models/meta.proto\x1a\x1eapi/proto/v1/models/file.proto\x1a#api/proto/v1/models/bank_card.proto\x1a%api/proto/v1/models/credentials.proto\x1a\x1fapi/proto/v1/common/enums.proto\"\xbd\x02\n" +
	"\x0fDataSaveRequest\x121\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1d.api.proto.v1.common.DataTypeR\x04type\x12-\n" +
	"\x04meta\x18\x02 \x01(\v2\x19.api.proto.v1.models.MetaR\x04meta\x12<\n" +
	"\tbank_card\x18\x03 \x01(\v2\x1d.api.proto.v1.models.BankCardH\x00R\bbankCard\x12D\n" +
	"\vcredentials\x18\x04 \x01(\v2 .api.proto.v1.models.CredentialsH\x00R\vcredentials\x12<\n" +
	"\vbinary_data\x18\x05 \x01(\v2\x19.api.proto.v1.models.FileH\x00R\n" +
	"binaryDataB\x06\n" +
	"\x04data\",\n" +
	"\x10DataSaveResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessageB9Z7github.com/apetsko/gophkeeper/protogen/api/proto/v1/rpcb\x06proto3"

var (
	file_api_proto_v1_rpc_data_save_proto_rawDescOnce sync.Once
	file_api_proto_v1_rpc_data_save_proto_rawDescData []byte
)

func file_api_proto_v1_rpc_data_save_proto_rawDescGZIP() []byte {
	file_api_proto_v1_rpc_data_save_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_rpc_data_save_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_rpc_data_save_proto_rawDesc), len(file_api_proto_v1_rpc_data_save_proto_rawDesc)))
	})
	return file_api_proto_v1_rpc_data_save_proto_rawDescData
}

var file_api_proto_v1_rpc_data_save_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_v1_rpc_data_save_proto_goTypes = []any{
	(*DataSaveRequest)(nil),    // 0: api.proto.v1.rpc.DataSaveRequest
	(*DataSaveResponse)(nil),   // 1: api.proto.v1.rpc.DataSaveResponse
	(common.DataType)(0),       // 2: api.proto.v1.common.DataType
	(*models.Meta)(nil),        // 3: api.proto.v1.models.Meta
	(*models.BankCard)(nil),    // 4: api.proto.v1.models.BankCard
	(*models.Credentials)(nil), // 5: api.proto.v1.models.Credentials
	(*models.File)(nil),        // 6: api.proto.v1.models.File
}
var file_api_proto_v1_rpc_data_save_proto_depIdxs = []int32{
	2, // 0: api.proto.v1.rpc.DataSaveRequest.type:type_name -> api.proto.v1.common.DataType
	3, // 1: api.proto.v1.rpc.DataSaveRequest.meta:type_name -> api.proto.v1.models.Meta
	4, // 2: api.proto.v1.rpc.DataSaveRequest.bank_card:type_name -> api.proto.v1.models.BankCard
	5, // 3: api.proto.v1.rpc.DataSaveRequest.credentials:type_name -> api.proto.v1.models.Credentials
	6, // 4: api.proto.v1.rpc.DataSaveRequest.binary_data:type_name -> api.proto.v1.models.File
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_api_proto_v1_rpc_data_save_proto_init() }
func file_api_proto_v1_rpc_data_save_proto_init() {
	if File_api_proto_v1_rpc_data_save_proto != nil {
		return
	}
	file_api_proto_v1_rpc_data_save_proto_msgTypes[0].OneofWrappers = []any{
		(*DataSaveRequest_BankCard)(nil),
		(*DataSaveRequest_Credentials)(nil),
		(*DataSaveRequest_BinaryData)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_rpc_data_save_proto_rawDesc), len(file_api_proto_v1_rpc_data_save_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_v1_rpc_data_save_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_rpc_data_save_proto_depIdxs,
		MessageInfos:      file_api_proto_v1_rpc_data_save_proto_msgTypes,
	}.Build()
	File_api_proto_v1_rpc_data_save_proto = out.File
	file_api_proto_v1_rpc_data_save_proto_goTypes = nil
	file_api_proto_v1_rpc_data_save_proto_depIdxs = nil
}
