// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/proto/v1/rpc/data_list.proto

package rpc

import (
	models "github.com/apetsko/gophkeeper/protogen/api/proto/v1/models"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DataListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataListRequest) Reset() {
	*x = DataListRequest{}
	mi := &file_api_proto_v1_rpc_data_list_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataListRequest) ProtoMessage() {}

func (x *DataListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_rpc_data_list_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataListRequest.ProtoReflect.Descriptor instead.
func (*DataListRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_rpc_data_list_proto_rawDescGZIP(), []int{0}
}

func (x *DataListRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *DataListRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type DataListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*models.Record       `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataListResponse) Reset() {
	*x = DataListResponse{}
	mi := &file_api_proto_v1_rpc_data_list_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataListResponse) ProtoMessage() {}

func (x *DataListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_rpc_data_list_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataListResponse.ProtoReflect.Descriptor instead.
func (*DataListResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_rpc_data_list_proto_rawDescGZIP(), []int{1}
}

func (x *DataListResponse) GetRecords() []*models.Record {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *DataListResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_api_proto_v1_rpc_data_list_proto protoreflect.FileDescriptor

const file_api_proto_v1_rpc_data_list_proto_rawDesc = "" +
	"\n" +
	" api/proto/v1/rpc/data_list.proto\x12\x10api.proto.v1.rpc\x1a api/proto/v1/models/record.proto\";\n" +
	"\x0fDataListRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"_\n" +
	"\x10DataListResponse\x125\n" +
	"\arecords\x18\x01 \x03(\v2\x1b.api.proto.v1.models.RecordR\arecords\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05countB9Z7github.com/apetsko/gophkeeper/protogen/api/proto/v1/rpcb\x06proto3"

var (
	file_api_proto_v1_rpc_data_list_proto_rawDescOnce sync.Once
	file_api_proto_v1_rpc_data_list_proto_rawDescData []byte
)

func file_api_proto_v1_rpc_data_list_proto_rawDescGZIP() []byte {
	file_api_proto_v1_rpc_data_list_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_rpc_data_list_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_rpc_data_list_proto_rawDesc), len(file_api_proto_v1_rpc_data_list_proto_rawDesc)))
	})
	return file_api_proto_v1_rpc_data_list_proto_rawDescData
}

var file_api_proto_v1_rpc_data_list_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_v1_rpc_data_list_proto_goTypes = []any{
	(*DataListRequest)(nil),  // 0: api.proto.v1.rpc.DataListRequest
	(*DataListResponse)(nil), // 1: api.proto.v1.rpc.DataListResponse
	(*models.Record)(nil),    // 2: api.proto.v1.models.Record
}
var file_api_proto_v1_rpc_data_list_proto_depIdxs = []int32{
	2, // 0: api.proto.v1.rpc.DataListResponse.records:type_name -> api.proto.v1.models.Record
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_v1_rpc_data_list_proto_init() }
func file_api_proto_v1_rpc_data_list_proto_init() {
	if File_api_proto_v1_rpc_data_list_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_rpc_data_list_proto_rawDesc), len(file_api_proto_v1_rpc_data_list_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_v1_rpc_data_list_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_rpc_data_list_proto_depIdxs,
		MessageInfos:      file_api_proto_v1_rpc_data_list_proto_msgTypes,
	}.Build()
	File_api_proto_v1_rpc_data_list_proto = out.File
	file_api_proto_v1_rpc_data_list_proto_goTypes = nil
	file_api_proto_v1_rpc_data_list_proto_depIdxs = nil
}
