// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/proto/v1/rpc/data_view.proto

package rpc

import (
	common "github.com/apetsko/gophkeeper/protogen/api/proto/v1/common"
	models "github.com/apetsko/gophkeeper/protogen/api/proto/v1/models"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DataViewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataViewRequest) Reset() {
	*x = DataViewRequest{}
	mi := &file_api_proto_v1_rpc_data_view_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataViewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataViewRequest) ProtoMessage() {}

func (x *DataViewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_rpc_data_view_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataViewRequest.ProtoReflect.Descriptor instead.
func (*DataViewRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_rpc_data_view_proto_rawDescGZIP(), []int{0}
}

func (x *DataViewRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DataViewResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  common.DataType        `protobuf:"varint,1,opt,name=type,proto3,enum=api.proto.v1.common.DataType" json:"type,omitempty"`
	Meta  *models.Meta           `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	// Types that are valid to be assigned to Data:
	//
	//	*DataViewResponse_BankCard
	//	*DataViewResponse_Credentials
	//	*DataViewResponse_BinaryData
	Data          isDataViewResponse_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataViewResponse) Reset() {
	*x = DataViewResponse{}
	mi := &file_api_proto_v1_rpc_data_view_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataViewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataViewResponse) ProtoMessage() {}

func (x *DataViewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_rpc_data_view_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataViewResponse.ProtoReflect.Descriptor instead.
func (*DataViewResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_rpc_data_view_proto_rawDescGZIP(), []int{1}
}

func (x *DataViewResponse) GetType() common.DataType {
	if x != nil {
		return x.Type
	}
	return common.DataType(0)
}

func (x *DataViewResponse) GetMeta() *models.Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *DataViewResponse) GetData() isDataViewResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *DataViewResponse) GetBankCard() *models.BankCard {
	if x != nil {
		if x, ok := x.Data.(*DataViewResponse_BankCard); ok {
			return x.BankCard
		}
	}
	return nil
}

func (x *DataViewResponse) GetCredentials() *models.Credentials {
	if x != nil {
		if x, ok := x.Data.(*DataViewResponse_Credentials); ok {
			return x.Credentials
		}
	}
	return nil
}

func (x *DataViewResponse) GetBinaryData() *models.File {
	if x != nil {
		if x, ok := x.Data.(*DataViewResponse_BinaryData); ok {
			return x.BinaryData
		}
	}
	return nil
}

type isDataViewResponse_Data interface {
	isDataViewResponse_Data()
}

type DataViewResponse_BankCard struct {
	BankCard *models.BankCard `protobuf:"bytes,3,opt,name=bank_card,json=bankCard,proto3,oneof"`
}

type DataViewResponse_Credentials struct {
	Credentials *models.Credentials `protobuf:"bytes,4,opt,name=credentials,proto3,oneof"`
}

type DataViewResponse_BinaryData struct {
	BinaryData *models.File `protobuf:"bytes,5,opt,name=binary_data,json=binaryData,proto3,oneof"`
}

func (*DataViewResponse_BankCard) isDataViewResponse_Data() {}

func (*DataViewResponse_Credentials) isDataViewResponse_Data() {}

func (*DataViewResponse_BinaryData) isDataViewResponse_Data() {}

var File_api_proto_v1_rpc_data_view_proto protoreflect.FileDescriptor

const file_api_proto_v1_rpc_data_view_proto_rawDesc = "" +
	"\n" +
	" api/proto/v1/rpc/data_view.proto\x12\x10api.proto.v1.rpc\x1a\x1eapi/proto/v1/models/meta.proto\x1a\x1eapi/proto/v1/models/file.proto\x1a#api/proto/v1/models/bank_card.proto\x1a%api/proto/v1/models/credentials.proto\x1a\x1fapi/proto/v1/common/enums.proto\"!\n" +
	"\x0fDataViewRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\xbe\x02\n" +
	"\x10DataViewResponse\x121\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1d.api.proto.v1.common.DataTypeR\x04type\x12-\n" +
	"\x04meta\x18\x02 \x01(\v2\x19.api.proto.v1.models.MetaR\x04meta\x12<\n" +
	"\tbank_card\x18\x03 \x01(\v2\x1d.api.proto.v1.models.BankCardH\x00R\bbankCard\x12D\n" +
	"\vcredentials\x18\x04 \x01(\v2 .api.proto.v1.models.CredentialsH\x00R\vcredentials\x12<\n" +
	"\vbinary_data\x18\x05 \x01(\v2\x19.api.proto.v1.models.FileH\x00R\n" +
	"binaryDataB\x06\n" +
	"\x04dataB9Z7github.com/apetsko/gophkeeper/protogen/api/proto/v1/rpcb\x06proto3"

var (
	file_api_proto_v1_rpc_data_view_proto_rawDescOnce sync.Once
	file_api_proto_v1_rpc_data_view_proto_rawDescData []byte
)

func file_api_proto_v1_rpc_data_view_proto_rawDescGZIP() []byte {
	file_api_proto_v1_rpc_data_view_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_rpc_data_view_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_rpc_data_view_proto_rawDesc), len(file_api_proto_v1_rpc_data_view_proto_rawDesc)))
	})
	return file_api_proto_v1_rpc_data_view_proto_rawDescData
}

var file_api_proto_v1_rpc_data_view_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_v1_rpc_data_view_proto_goTypes = []any{
	(*DataViewRequest)(nil),    // 0: api.proto.v1.rpc.DataViewRequest
	(*DataViewResponse)(nil),   // 1: api.proto.v1.rpc.DataViewResponse
	(common.DataType)(0),       // 2: api.proto.v1.common.DataType
	(*models.Meta)(nil),        // 3: api.proto.v1.models.Meta
	(*models.BankCard)(nil),    // 4: api.proto.v1.models.BankCard
	(*models.Credentials)(nil), // 5: api.proto.v1.models.Credentials
	(*models.File)(nil),        // 6: api.proto.v1.models.File
}
var file_api_proto_v1_rpc_data_view_proto_depIdxs = []int32{
	2, // 0: api.proto.v1.rpc.DataViewResponse.type:type_name -> api.proto.v1.common.DataType
	3, // 1: api.proto.v1.rpc.DataViewResponse.meta:type_name -> api.proto.v1.models.Meta
	4, // 2: api.proto.v1.rpc.DataViewResponse.bank_card:type_name -> api.proto.v1.models.BankCard
	5, // 3: api.proto.v1.rpc.DataViewResponse.credentials:type_name -> api.proto.v1.models.Credentials
	6, // 4: api.proto.v1.rpc.DataViewResponse.binary_data:type_name -> api.proto.v1.models.File
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_api_proto_v1_rpc_data_view_proto_init() }
func file_api_proto_v1_rpc_data_view_proto_init() {
	if File_api_proto_v1_rpc_data_view_proto != nil {
		return
	}
	file_api_proto_v1_rpc_data_view_proto_msgTypes[1].OneofWrappers = []any{
		(*DataViewResponse_BankCard)(nil),
		(*DataViewResponse_Credentials)(nil),
		(*DataViewResponse_BinaryData)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_rpc_data_view_proto_rawDesc), len(file_api_proto_v1_rpc_data_view_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_v1_rpc_data_view_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_rpc_data_view_proto_depIdxs,
		MessageInfos:      file_api_proto_v1_rpc_data_view_proto_msgTypes,
	}.Build()
	File_api_proto_v1_rpc_data_view_proto = out.File
	file_api_proto_v1_rpc_data_view_proto_goTypes = nil
	file_api_proto_v1_rpc_data_view_proto_depIdxs = nil
}
