// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/proto/v1/rpc/data_delete.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DataDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataDeleteRequest) Reset() {
	*x = DataDeleteRequest{}
	mi := &file_api_proto_v1_rpc_data_delete_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataDeleteRequest) ProtoMessage() {}

func (x *DataDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_rpc_data_delete_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataDeleteRequest.ProtoReflect.Descriptor instead.
func (*DataDeleteRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_rpc_data_delete_proto_rawDescGZIP(), []int{0}
}

func (x *DataDeleteRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DataDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataDeleteResponse) Reset() {
	*x = DataDeleteResponse{}
	mi := &file_api_proto_v1_rpc_data_delete_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataDeleteResponse) ProtoMessage() {}

func (x *DataDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_rpc_data_delete_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataDeleteResponse.ProtoReflect.Descriptor instead.
func (*DataDeleteResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_rpc_data_delete_proto_rawDescGZIP(), []int{1}
}

func (x *DataDeleteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_proto_v1_rpc_data_delete_proto protoreflect.FileDescriptor

const file_api_proto_v1_rpc_data_delete_proto_rawDesc = "" +
	"\n" +
	"\"api/proto/v1/rpc/data_delete.proto\x12\x10api.proto.v1.rpc\"#\n" +
	"\x11DataDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\".\n" +
	"\x12DataDeleteResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessageB9Z7github.com/apetsko/gophkeeper/protogen/api/proto/v1/rpcb\x06proto3"

var (
	file_api_proto_v1_rpc_data_delete_proto_rawDescOnce sync.Once
	file_api_proto_v1_rpc_data_delete_proto_rawDescData []byte
)

func file_api_proto_v1_rpc_data_delete_proto_rawDescGZIP() []byte {
	file_api_proto_v1_rpc_data_delete_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_rpc_data_delete_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_rpc_data_delete_proto_rawDesc), len(file_api_proto_v1_rpc_data_delete_proto_rawDesc)))
	})
	return file_api_proto_v1_rpc_data_delete_proto_rawDescData
}

var file_api_proto_v1_rpc_data_delete_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_v1_rpc_data_delete_proto_goTypes = []any{
	(*DataDeleteRequest)(nil),  // 0: api.proto.v1.rpc.DataDeleteRequest
	(*DataDeleteResponse)(nil), // 1: api.proto.v1.rpc.DataDeleteResponse
}
var file_api_proto_v1_rpc_data_delete_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_v1_rpc_data_delete_proto_init() }
func file_api_proto_v1_rpc_data_delete_proto_init() {
	if File_api_proto_v1_rpc_data_delete_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_rpc_data_delete_proto_rawDesc), len(file_api_proto_v1_rpc_data_delete_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_v1_rpc_data_delete_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_rpc_data_delete_proto_depIdxs,
		MessageInfos:      file_api_proto_v1_rpc_data_delete_proto_msgTypes,
	}.Build()
	File_api_proto_v1_rpc_data_delete_proto = out.File
	file_api_proto_v1_rpc_data_delete_proto_goTypes = nil
	file_api_proto_v1_rpc_data_delete_proto_depIdxs = nil
}
