services:
  frontend:
    depends_on:
      - backend
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:443"
    container_name: gophkeeper_frontend
    networks:
      - gophkeeper_net
    volumes:
      - certs_data:/usr/share/nginx/html/certs

  backend:
    depends_on:
      - gophkeeper_minio_build
      - gophkeeper_postgres_build
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - "8082:8082"
    container_name: gophkeeper_backend
    networks:
      - gophkeeper_net
    volumes:
      - certs_data:/app/certs

  gophkeeper_minio_build:
    container_name: gophkeeper_minio
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ../../gophstorage_docker/minio/data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address :9001
    networks:
      - gophkeeper_net
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  create-bucket:
    image: minio/mc:latest
    environment:
      MC_HOST_minio: http://${minioadmin}:${minioadmin}@gophkeeper_minio:9000
    entrypoint:
      - sh
      - -c
      - |
        until mc ls minio > /dev/null 2>&1; do
          sleep 0.5
        done

        mc mb gophkeeper_minio/post-bucket

  gophkeeper_postgres_build:
    image: postgres:17
    container_name: gophkeeper_postgres
    restart: always
#    ports:
#      - "25432:5432"
    environment:
      POSTGRES_USER: gophkeeper_user
      POSTGRES_PASSWORD: gophkeeper_pass
      POSTGRES_DB: gophkeeper_db
    volumes:
      - ../../gophstorage_docker/postgres/data:/var/lib/postgresql/data
    networks:
      - gophkeeper_net

networks:
  gophkeeper_net:
    driver: bridge

volumes:
  certs_data:
    driver: local
