services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:443"
    container_name: gophkeeper_frontend
    networks:
      - gophkeeper_net
    volumes:
      - certs_data:/usr/share/nginx/html/certs

  backend:
    depends_on:
      - gophkeeper_postgres_build
      - gophkeeper_minio_build
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
    container_name: gophkeeper_backend
    networks:
      - gophkeeper_net
    volumes:
      - certs_data:/app/certs

  gophkeeper_minio_build:
    image: minio/minio:latest
    container_name: gophkeeper_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - ../gophstorage/minio/data:/data
      - ../gophstorage/minio/config:/root/.minio
    networks:
      - gophkeeper_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5

  gophkeeper_postgres_build:
    image: postgres:17
    container_name: gophkeeper_postgres
    restart: always
    ports:
      - "25432:5432"
    environment:
      POSTGRES_USER: gophkeeper_user
      POSTGRES_PASSWORD: gophkeeper_pass
      POSTGRES_DB: gophkeeper_db
    volumes:
      - ../gophstorage/postgres/data:/var/lib/postgresql/data
    networks:
      - gophkeeper_net

networks:
  gophkeeper_net:
    driver: bridge

volumes:
  certs_data:
    driver: local
