services:
  frontend:
    depends_on:
      - backend
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:443"
    container_name: gophkeeper_frontend
    networks:
      - gophkeeper_net
    volumes:
      - certs_data:/usr/share/nginx/html/certs

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend.local
    ports:
      - "8082:8082"
    container_name: gophkeeper_backend
    networks:
      - gophkeeper_net
    volumes:
      - certs_data:/app/certs

networks:
  gophkeeper_net:
    driver: bridge

volumes:
  certs_data:
    driver: local
