// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/proto/v1/common/enums.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DataType int32

const (
	DataType_DATA_TYPE_UNSPECIFIED DataType = 0
	DataType_DATA_TYPE_BANK_CARD   DataType = 1
	DataType_DATA_TYPE_CREDENTIALS DataType = 2
	DataType_DATA_TYPE_BINARY_DATA DataType = 3
)

// Enum value maps for DataType.
var (
	DataType_name = map[int32]string{
		0: "DATA_TYPE_UNSPECIFIED",
		1: "DATA_TYPE_BANK_CARD",
		2: "DATA_TYPE_CREDENTIALS",
		3: "DATA_TYPE_BINARY_DATA",
	}
	DataType_value = map[string]int32{
		"DATA_TYPE_UNSPECIFIED": 0,
		"DATA_TYPE_BANK_CARD":   1,
		"DATA_TYPE_CREDENTIALS": 2,
		"DATA_TYPE_BINARY_DATA": 3,
	}
)

func (x DataType) Enum() *DataType {
	p := new(DataType)
	*p = x
	return p
}

func (x DataType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DataType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_v1_common_enums_proto_enumTypes[0].Descriptor()
}

func (DataType) Type() protoreflect.EnumType {
	return &file_api_proto_v1_common_enums_proto_enumTypes[0]
}

func (x DataType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DataType.Descriptor instead.
func (DataType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_v1_common_enums_proto_rawDescGZIP(), []int{0}
}

var File_api_proto_v1_common_enums_proto protoreflect.FileDescriptor

const file_api_proto_v1_common_enums_proto_rawDesc = "" +
	"\n" +
	"\x1fapi/proto/v1/common/enums.proto\x12\x13api.proto.v1.common*t\n" +
	"\bDataType\x12\x19\n" +
	"\x15DATA_TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13DATA_TYPE_BANK_CARD\x10\x01\x12\x19\n" +
	"\x15DATA_TYPE_CREDENTIALS\x10\x02\x12\x19\n" +
	"\x15DATA_TYPE_BINARY_DATA\x10\x03B<Z:github.com/apetsko/gophkeeper/protogen/api/proto/v1/commonb\x06proto3"

var (
	file_api_proto_v1_common_enums_proto_rawDescOnce sync.Once
	file_api_proto_v1_common_enums_proto_rawDescData []byte
)

func file_api_proto_v1_common_enums_proto_rawDescGZIP() []byte {
	file_api_proto_v1_common_enums_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_common_enums_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_common_enums_proto_rawDesc), len(file_api_proto_v1_common_enums_proto_rawDesc)))
	})
	return file_api_proto_v1_common_enums_proto_rawDescData
}

var file_api_proto_v1_common_enums_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_v1_common_enums_proto_goTypes = []any{
	(DataType)(0), // 0: api.proto.v1.common.DataType
}
var file_api_proto_v1_common_enums_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_v1_common_enums_proto_init() }
func file_api_proto_v1_common_enums_proto_init() {
	if File_api_proto_v1_common_enums_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_common_enums_proto_rawDesc), len(file_api_proto_v1_common_enums_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_v1_common_enums_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_common_enums_proto_depIdxs,
		EnumInfos:         file_api_proto_v1_common_enums_proto_enumTypes,
	}.Build()
	File_api_proto_v1_common_enums_proto = out.File
	file_api_proto_v1_common_enums_proto_goTypes = nil
	file_api_proto_v1_common_enums_proto_depIdxs = nil
}
