name: Go unit tests

on:
  push:
    branches: [main, master, dev]
  pull_request:
    branches: [main, master, dev]

jobs:
  unittest:
    runs-on: ubuntu-latest
    container: golang:1.24.2

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: gophkeeper_user
          POSTGRES_PASSWORD: gophkeeper_pass
          POSTGRES_DB: gophkeeper_db
        options: >-
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 25432:5432

      minio:
        image: minio/minio
        ports:
          - 9000:9000
        options: >-
          --health-cmd "curl -f http://minio:9000/minio/health/ready || exit 1"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5
          --entrypoint minio
        env:
          MINIO_ROOT_USER: minioadmin
          MINIO_ROOT_PASSWORD: minioadmin

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24.2"

      - name: Verify dependencies
        run: go mod verify

      - name: Build
        run: go build ./cmd/server/main.go

      - name: Run go vet
        run: go vet ./...

      - name: Run tests
        env:
          CI: "true"
        run: go test -race -v ./...
